Add form bug / Styling Updates
nss-evening-cohort-14/whalom-park-dashboard-whalom-park-dashboard pull request #103
Opened 2021-04-10 17:14 UTC by thedigitalmenagerie

[X] Made styling more consistent
[X] Improved Visibility of Card Information
[X] Fixed Form Toggle Bug
[X] Fixed Vendor and Event form not printing

2021-04-10 17:28 UTC, GonzalesMatthew approved these changes

2021-04-10 17:31 UTC, HunterJuneau requested changes
Delete button on Vendors page isn't working.

2021-04-10 18:50 UTC, cmeffley approved these changes

2021-04-10 18:50 UTC, HunterJuneau approved these changes

2021-04-10 18:59 UTC, GonzalesMatthew requested changes
Would like to review branch again after merge has been completed.

2021-04-10 19:01 UTC, GonzalesMatthew approved these changes

2021-04-11 16:41 UTC, HunterJuneau approved these changes
The styling looks great!

2021-04-12 22:46 UTC, merged